# Yes this is a pod file living in a Ruby project.
#
# POD is a very nice format to write documentation in, and RDoc does
# not appear to be able to properly export to manpages, hence why I
# decided to use POD. The manpage that also lives in the git repo
# is the one that is distributed. The POD only lives in the git repo
# and is used to generate the manpage.

=head1 NAME

wwine - a simple wine(1) wrapper

=head1 SYNOPSIS

wwine I<(WWINE PARAMETERS)> I<PROGRAM> -- I<[PROGRAM ARGUMENTS]>

=head1 DESCRIPTION

B<wwine> is a a wine(1) wrapper. It wraps various flavours of wine
(including vanilla wine and crossover office/games) into a single
unified interface, complete with full bottle support for all
of them (including vanilla wine).

It integrates well with all flavours, so for instance applications
installed using crossover will be managable through the usual crossover
interface.

For vanilla wine it uses WINEPREFIX to achieve bottle support,
creating bottles as ~/.winebottle_[BOTTLE_NAME].

=head1 OPTIONS

=over

=item B<-h, --help>

Display the help screen

=item B<-w, --wine> I<FLAVOUR>

Use the supplied flavour of wine. The default is to use vanilla wine.

Possible paramters: wine, cxgames, cxoffice, cedega, cxg (alias for cxgames),
cxo (alias for cxoffice) or /path/to/a/wine.binary

See also I<--cxinstalldir>.

=item B<-b, --bottle> I<NAME>

Use the bottle with the name supplied. For cxgames, cxoffice or cedega
it uses the flavours builtin bottle support. For vanilla wine it sets
WINEPREFIX to use ~/.winebottle_I<NAME>. It defaults to no bottle,
in which case vanilla wine will use ~/.wine, cxoffice/cxgames will
use the bottle defined as default and for cedega a bottle named 'wwineFolder'
will be used.

=item B<-k, --kill>

Attempt to kill all running wine processes. See also I<--drykill>

=item B<--drykill>

Print what I<--kill> would have done, without actually doing anything.

=item B<-c, --cxinstalldir> I<PATH>

Use the supplied path as the path to either a crossover office/games install
directory, or as a directory that contains a cxoffice and/or cxgames directory.

=item B<--wrap> I<PATH>

Generate a wrapper script of the current command-line and write it to
I<PATH>. Simply write a wwine command as usual, and append --wrap I<PATH>
to it, and wwine will generate a wrapper script that you can use to
run that command with at any later time so you don't have to remember
or retype it every time.

Generally I<PATH> should be somewhere in your $PATH (ie. ~/bin/somecommand)
so that you can start the command from anywhere.

By default the wrapper script will change directory to the directory
you were in when you created it, but you can use B<--wrapdir> to explicitly
supply one.

The wrapper script also contains some basic code that ensures that
even if you remove or move wwine, the wrapper script will keep working.

=item B<--wrapdir> I<PATH>

Change directory to I<PATH> in the wrapper script generated by I<--wrap>.
If this is not supplied wwine will change to the directory that you
were in at the time the wrapper script was created.

=item B<-v, --verbose>

Increase verbosity. When this is present wwine will tell you the exact
commands it is running.

=item B<--man>

Show the manpage. Normally 'man wwine' would do, but when wwine is
installed from a rubygem the wwine manpage isn't placed anywhere
in man(1)'s path, this will autodetect its location and issue man
directly on the wwine.1 file (and thus work even when 'man wwine'
does not).

=back

=head1 EXAMPLES

=over

=item I<wwine file.exe>

The same as 'WINEDEBUG=-all wine file.exe'

=item I<wwine -b file file.exe>

Runs file.exe in wine, using the 'file' bottle.

=item I<wwine -w cxg -b file file.exe>

Runs file.exe in crossover games using the cxgames 'file' bottle

=item I<wwine --cxinstalldir ~/cxgames7.0/ -w cxg -b file file.exe>

Runs file.exe in the version of crossover games that is installed at
I<~/cxgames7.0>, using the cxgames 'file' bottle.

--cxinstalldir can be useful to run something in a version of cxgames/cxoffice
other than your primary one. Ie. if a regression causes it to not run in a
later version.

=item I<wwine -w cxg -b file file.exe --wrap ~/bin/startFile>

This causes wwine to create a wrapper shell script at ~/bin/startFile.
When you run that wrapper script, it will cd to the directory
you were in when the script was created, and issue a wwine command
with the above arguments. If you remove/uninstall wwine, the
wrapper script will most likely keep working as it has a fallback
that gets run if wwine can not be found.

If you are not in the directory that you want wwine to run the file
from, you may use --wrapdir to explicitly specify it.

=item I<wwine -k>

Will make wwine attempt to kill all running wine processes on this system.

=back

=head1 DEPENDENCIES

Requires at least one of wine, cxoffice, cxgames or cedega.

=head1 HELP/SUPPORT

If you need help or support please visit the website at L<http://random.zerodogg.org/wwine>

=head1 BUGS AND LIMITATIONS

If you find a bug, please report it at L<http://random.zerodogg.org/wwine/bugs>

=head1 AUTHOR

B<wwine> is written by Eskild Hustvedt <I<code at zerodogg dot org>>

=head1 LICENSE AND COPYRIGHT

Copyright (C) Eskild Hustvedt 2009

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
